function data1 = importfile1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATALOG20200519145647063 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  DATALOG20200519145647063 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Datalog20200519145647063 = importfile("C:\HOME\Èeské vysoké uèení technické v Praze\Team-PV Accu - Documents\Zpracování ÈSN 50530\GW10 6500Wnom\Data log 2020-05-19-14-56-47-063.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-May-2020 14:41:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TIMESTAMP", "CH1DCV", "CH1DCI", "CH1RMSW", "CH1ACV", "CH1ACI", "CH1MPP", "CH1KWH", "CH1MPPW", "CH1MPPV", "CH1MPPI", "VarName12"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, [1, 12], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], "TrimNonNumeric", true);
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], "DecimalSeparator", ",");
opts = setvaropts(opts, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], "ThousandsSeparator", ".");
opts = setvaropts(opts, [1, 12], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data1 = readtable(filename, opts);

end