function data2 = importfile2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GW106500EURO = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GW106500EURO = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  gw106500euro = importfile("C:\HOME\Èeské vysoké uèení technické v Praze\Team-PV Accu - Documents\Zpracování ÈSN 50530\GW10 6500Wnom\gw10-6500euro.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-May-2020 14:34:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["tsnorm1G1Narrow", "utrms1G1NarrowV", "itrms1G1NarrowA", "p1G1NarrowW", "utrms2G1NarrowV", "itrms2G1NarrowA", "p2G1NarrowW", "utrms3G1NarrowV", "itrms3G1NarrowA", "p3G1NarrowW", "utrms1G2NarrowV", "itrms1G2NarrowA", "p1G2NarrowW", "p_SUMG1NarrowW", "hihd_SUMG1Narrow", "hihd1G1Narrow", "hihd2G1Narrow", "hihd3G1Narrow", "huhd_SUMG1Narrow", "huhd1G1Narrow", "huhd2G1Narrow", "huhd3G1Narrow", "pf_SUMG1Narrow", "pf1G1Narrow", "pf2G1Narrow", "pf3G1Narrow", "bpam1G1Narrow0W", "bpam2G1Narrow0W", "bpam3G1Narrow0W", "q1G1Narrowvar", "q2G1Narrowvar", "q3G1Narrowvar", "q_SUMG1Narrowvar"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 15, 19], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data2 = readtable(filename, opts);

end